groonga-httpd: show error details on groonga-httpd configure error

diff --git a/src/httpd/configure b/src/httpd/configure
--- a/src/httpd/configure
+++ b/src/httpd/configure
@@ -31,7 +31,6 @@ relative_nginx_directory="vendor/nginx-${nginx_version}"
 nginx_directory="${top_srcdir}/${relative_nginx_directory}"
 
 export GROONGA_HTTPD_IN_TREE=yes
-cat "${top_builddir}/groonga-httpd-conf.sh"
 . "${top_builddir}/groonga-httpd-conf.sh"
 
 eval "$(${top_builddir}/libtool --config)"
@@ -83,6 +82,7 @@ fi
 
 cd "${nginx_directory_in_build_directory}"
 
+set +e
 auto/configure \
   --prefix="${GROONGA_HTTPD_PREFIX}" \
   --sbin-path="${GROONGA_HTTPD_BIN_PATH}" \
@@ -95,6 +95,14 @@ auto/configure \
   --with-ld-opt="${ld_opt}" \
   --with-http_stub_status_module \
   ${configure_args}
+exit_code=$?
+set -e
+
+if [ ${exit_code} -ne 0 ]; then
+  echo "Failed to configure groonga-httpd. Details:"
+  cat objs/autoconf.err
+  exit ${exit_code}
+fi
 
 if [ "${GROONGA_HTTPD_DEBUG}" = "yes" ]; then
   objs_makefile_backup="objs/Makefile.with-debug-flags"
