groonga-httpd-restart: add missing wait for PID file creation

diff --git a/data/scripts/groonga-httpd-restart b/data/scripts/groonga-httpd-restart
--- a/data/scripts/groonga-httpd-restart
+++ b/data/scripts/groonga-httpd-restart
@@ -64,6 +64,11 @@ OLD_PID=$(cat ${PID_FILE})
 start_master ${OLD_PID}
 
 if ! wait_until [ -f ${OLD_PID_FILE} ]; then
+    echo "Failed to create old PID file: <${PID_FILE}>"
+    exit 1
+fi
+
+if ! wait_until [ -f ${PID_FILE} ]; then
     echo "Failed to start new groonga-httpd master."
     exit 1
 fi
