httpd deb: revert to previous version
refs #1456

diff --git a/packages/debian/groonga-httpd.init b/packages/debian/groonga-httpd.init
--- a/packages/debian/groonga-httpd.init
+++ b/packages/debian/groonga-httpd.init
@@ -175,8 +175,21 @@ case "$1" in
 	;;
     restart)
 	log_daemon_msg "Restarting $DESC" "$NAME"
-	do_restart
-	log_end_msg $?
+	do_stop
+	case "$?" in
+	    0|1)
+		do_start
+		case "$?" in
+		    0) log_end_msg 0 ;;
+		    1) log_end_msg 1 ;; # Old process is still running
+		    *) log_end_msg 1 ;; # Failed to start
+		esac
+		;;
+	    *)
+		# Failed to stop
+		log_end_msg 1
+		;;
+	esac
 	;;
     status)
 	do_status
